### ISSUE TITLE
compile Racket symbols to js Symbol values?

### ISSUE THREAD

**Issue by stchang** [racketscript/racketscript#246]
js has Symbol values now: https://developer.mozilla.org/en-US/docs/Glossary/Symbol

Would it be appropriate to compile Racket symbols to these js values?

(@samth Do you know if these would be compatible with Racket symbols, eg interning?)

**Comment by samth** [comment]
Basically, yes. Symbol.for creates an interned symbol. Symbol("foo") is uninterned. Symbol() is basically gensym.

**Comment by stchang** [comment]
Oh so it should be straightforward then and we can get rid of our `Symbol` class, nice.

**Comment by DarrenN** [comment]
I'm working my way through the source to understand how the AST is compiled to the IL and then to JS, so please bear with me. It looks like this is where `symbol?`s are tagged(?) to call the `core.Symbol` class: https://github.com/racketscript/racketscript/blob/master/racketscript-compiler/racketscript/compiler/transform.rkt#L617

Am I correct in thinking that this is where we would instead mark `symbol?`s to use [native Symbols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) instead?

**Comment by vishesh** [comment]
Hey, thanks for taking this. Yes, that sounds right. You can also probably just replace the part where we do `(ILApp 'core.Symbol.make)` to just `(ILApp 'Symbol ... )` as it basically looks just like function application. However,  what you propose is IMO better.

**Comment by stchang** [comment]
I'll be able to take a look at this early next week. Thanks again for doing this.
