### ISSUE TITLE
Final expression not printed

### ISSUE THREAD

**Issue by gamburgm** [racketscript/racketscript#255]
Not sure if this was a decision made by the team or not, but I noticed that the module
```racket
#lang racketscript/base

(+ 2 2)
```
Doesn't actually print anything. I think it would be nice if the last expression of a module got wrapped in a `displayln` effectively.

**Comment by jakeisnt** [comment]
I think the status quo is fine even though it diverges from Racket semantics.

If the javascript module output of the racketscript file is used in the browser, printing the return value of the last expression of that file to the in-browser console could be confusing and expose undesirable information to the end user (even though it's hiding in the dev tools).

**Comment by stchang** [comment]
Closing this bc I agree the current behavior is fine. Re-open if there's another use case we're not thinking of.
