### ISSUE TITLE
Is RacketScript participating in Hactoberfest?

### ISSUE THREAD

**Issue by spdegabrielle** [racketscript/racketscript#258]
https://hacktoberfest.digitalocean.com/

**Comment by vishesh** [comment]
I personally wasn't tracking the event, and seems like we missed the US one. Not sure what is required to organize, would you like to host the Europe event if you have bandwidth?

**Comment by spdegabrielle** [comment]
To participate 
- [ ] Need to add topic 'hacktoberfest' to repo
- [ ] Participants need to signup on official website
- [ ] Maintainers can mark a PR accepted for Havtobe fest by either (a) giving  an approving review, (b) merge pr, or (c) labeling the pr 'hacktoberfest-accepted' label.

I'm not qualified to assess PRs to to RacketScript repo

I can publicise that you are open to submissions on social media related to racket scheme lisp

Let me know what you think

S.

**Comment by sorawee** [comment]
Just want to chime in to say that Hacktoberfest usually attracts a lot of low quality PRs (whitespace changes, wording changes, etc). I don't know if the rules have changed to disqualify these kind of PRs, and even with the rule change, it might still attract these kind of PRs anyway.

So I think we should be careful before deciding to participate.

**Comment by spdegabrielle** [comment]
@sorawee I was hoping the registration and criteria for acceptance (positive review, pull or label by maintainer) might change that.

An option might be create a GitHub fork that has topic 'hactoberfest', as a staging ground. 

If the PRs are low quality, or it is otherwise more trouble than it is worth: delete the fork. (opting out of hactoberfest)
