### ISSUE TITLE
old link on wiki troubleshooting page

### ISSUE THREAD

**Issue by spdegabrielle** [racketscript/racketscript#259]
https://github.com/racketscript/racketscript/wiki/Troubleshooting

links to 
https://github.com/vishesh/racketscript/blob/master/CONTRIBUTING.md#using-multiple-racket-versions
instead of 
https://github.com/racketscript/racketscript/blob/master/CONTRIBUTING.md#using-multiple-racket-versions

**Comment by stchang** [comment]
updated, thanks.
