### ISSUE TITLE
assignment? 

### ISSUE THREAD

**Issue by jakeisnt** [racketscript/racketscript#265]
a common pattern in front-end javascript is to set the innerHTML of a document: i. e. document.getElementById("elem-id").innerHTML = <div/> or similar.

I'm having difficulty finding an analogue to this in racketscript (aside from defining a custom prelude) - set! and $/:= both seem to produce compile time errors.

Is there a way to express this in racketscript? If so, how?

**Comment by stchang** [comment]
If you are looking to do assignment to js variables, then yes the `$/:=` ffi call is what you want.

You can see several uses in the racketscript playground app:
https://github.com/racketscript/racketscript-playground/blob/master/client.rkt
https://github.com/racketscript/racketscript-playground/blob/master/app.rkt

What error are you getting?

**Comment by jakeisnt** [comment]
Thanks for the quick response!

Here's a minimal example that I'm unable to get working, even though the documentation suggests that this is the correct approach:

``` racket
#lang racketscript/base

(require racketscript/interop)

(define (get-elem id)
  ($ (#js*.document.getElementById id) 'innerHTML))

(define (display-count)
  ($/:= (get-elem "root") "test"))

(display-count) 

```

I receive some red squigglys in my editor and a compile time error for providing the expression (get-elem...) to $/:=. I've tried casting the strings to JavaScript strings as the FFI docs suggest but with no success.

**Comment by stchang** [comment]
Ah yes, an ffi call has to be raw js. You can't interleave a racketscript function call like that. 

It will work if you inline `get-elem`, for example:
http://play.racketscript.org/#gist/12ed46e40ddbb347c774b41634bcc493
```racket
#lang racketscript/base

(require racketscript/interop)

(define (change-html id)
  ($/:= ($ (#js*.parent.document.getElementById id) 'innerHTML) #js"test"))

(change-html #js"btn-compile") ; changes compile button
```

Though your example suggests that a quasiquote-like "escape" could be useful feature request?

**Comment by jakeisnt** [comment]
Got it, thanks! Absolutely agree that some sort of escape delimiter - to denote some s-expression that should be evaluated as javscript implicitly - would be a good idea.
