### ISSUE TITLE
If an exported name has the same name as a global one it gets undefined if it is assigned that global value

### ISSUE THREAD

**Issue by kurinoku** [racketscript/racketscript#312]
So, I don't know why I did it but this is the example I have

```racket
#lang racketscript/base
(provide Promise)
(define Promise #js*.Promise)
```

this resulted in
```js
import * as $rjs_core from "../../../runtime/core.js";
import * as M0 from "../../../links/racketscript-compiler/racketscript/private/interop.rkt.js";
console.log(Promise);
var Promise = Promise;
var __rjs_quoted__ = {};
export { __rjs_quoted__, Promise };
```

which in another module the expression `M0.Promise` returned `undefined`.

This could be an issue, or it might be intended given the properties of `var` and whatnot.

**Comment by kclapper** [comment]
Hello!

I think this is intended behavior. If you try something like this in Node:
```javascript
console.log(Promise)
var Promise = Promise
```
the result is `undefined`, while:
```javascript
console.log(Promise)
// var Promise = Promise
```
results in `[Function: Promise]`. 

It may just be a JS oddity.
