### ISSUE TITLE
Module dependencies are not always recompiled when updated

### ISSUE THREAD

**Issue by kclapper** [racketscript/racketscript#313]
If a change is made to a module's dependency, but the module itself is left alone, the dependency is not recompiled.

For example, if you have the file `has-dependency.rkt`:
    
    #lang racket 
    
    (require "dependency.rkt")

    (println (format "~a" (add 5)))

and another file `dependency.rkt`:

    #lang racket 
    
    (provide add)

    (define (add n)
      (+ n 2))

If you compile `has-dependency.rkt`, then change the `2` in `dependency.rkt` to a `1` and recompile it again, the resulting Javascript code still prints out "7" instead of "6".

**Comment by kclapper** [comment]
This can be fixed by checking for stale modules in the cached timestamps ahead of the compilation loop in `racket->js`. Then, the stale modules can be added to the queue to be recompiled. This solution seems to work for me, I'll try and write tests and submit a pull request soon.

**Comment by stchang** [comment]
fixed with #314
